In [11]:
list1 = [1,2,3,4,5] 

print(list1)

list2 = ["Adhir1",88,list1,True]
print(list2)

[1, 2, 3, 4, 5]
['Adhir1', 88, [1, 2, 3, 4, 5], True]


In [18]:
import numpy as np

# NUMPY = Numeric python
data type of numpy is ndarray (i.e  n-dimensional array)

In [27]:
np1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(np1)
print(np1.shape ) # this gives the number of items in array  

[0 1 2 3 4 5 6 7 8 9]
(10,)


# nparray with Range



In [32]:
np2= np.arange(10)
print(np2)



[0 1 2 3 4 5 6 7 8 9]



# Range with step


In [35]:
np3 = np.arange(0,10,2)
print(np3)

[0 2 4 6 8]


# array of zeros


In [36]:
np4 = np.zeros(10)
print(np4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# Multidimensional Zeros

In [37]:
np5 = np.zeros((2,10))
print(np5)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [41]:
np6 = np.full((10),9)#full is used for getting the array of any number we want instead of zeros 
print(np6)

# Multidimensional full

np7 = np.full((2,10),7)
print(np7)

[9 9 9 9 9 9 9 9 9 9]
[[7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]]


# Converting python list to numpy array

In [42]:
my_list = [1,2,3,4,5]
np8 = np.array(my_list)
print(np8)

[1 2 3 4 5]
