In [1]:
import numpy as np

# Slicing Numpy Arrays

In [4]:
np1 = np.array([1,2,3,4,5,6,7,8,9])

# To return 2,3,4,5

print(np1[1:5])

print(np1[3:]) # returns from third indexed number till the end

[2 3 4 5]
[4 5 6 7 8 9]


# Negative slicing

In [8]:
print(np1[-7:-1])

[3 4 5 6 7 8]


In [11]:
#steps
    
print(np1[1:7:2])

# steps in entire array

print(np1[::2])
print(np1[::3])

[2 4 6]
[1 3 5 7 9]
[1 4 7]


# Slicing 2d array

In [21]:
np2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

# pulling a single item

print(np2[1,2])

print(np2[0:1,2:4])  # prints 3,4

print(np2[:,1:4]) # prints [2,3,4] [7,8,9]

8
[[3 4]]
[[2 3 4]
 [7 8 9]]
