# Numpy Universal functions

In [1]:
import numpy as np 

In [6]:
np1 = np.array([1,2,3,4,5,6,7,8,9])

print(np1)

[1 2 3 4 5 6 7 8 9]


In [7]:
# Square root of each element 

print(np.sqrt(np1))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]


In [9]:
# Absolute value
np2 = np.array([-1,-2,-3,-4,-5,-6,-7,-8,-9])
print(np2)
print(np.absolute(np1))

[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[1 2 3 4 5 6 7 8 9]


In [10]:
# Exponnents 
print(np.exp(np1))

[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]


In [12]:
# Min/Max

print(np.min(np1))
print(np.max(np1))

1
9


In [14]:
# is sign neg or pos
print(np.sign(np1)) # returns -1 for negative , 0  for zero and 1 for positive
print(np.sign(np2))

[1 1 1 1 1 1 1 1 1]
[-1 -1 -1 -1 -1 -1 -1 -1 -1]


In [15]:
# Trigonometric functions 

print(np.sin(np1))
print(np.cos(np1))
print(np.tan(np1))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
  0.87144798 -6.79971146 -0.45231566]
