
#  Shape  and Reshape

In [1]:
import numpy as np 

In [9]:
# creating 1-D array and get shape 

np1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(np1)

print(np1.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [6]:
'''
# creating 2-D array and get shape 

np2 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])


print(np2)

print(np2.shape)
'''

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


In [10]:
'''# Reshaping into 2-D array

np3 = np1.reshape(3,4)

print(np3)

print(np3.shape)
'''

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [12]:
#  Reshaping into 3-D array

np4 = np1.reshape(2,3,2)

print(np4)

print(np4.shape)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


In [13]:
# Flatten to 1-D array
np5 = np4.reshape(-1)

print(np5)

print(np5.shape)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
