# Sorting Numpy Array

In [1]:
import numpy as np

In [2]:
# Numerial sorting

np1 = np.array([2,7,4,0,8,16])

print(np1)

print(np.sort(np1))  # sorts in ascending order

[ 2  7  4  0  8 16]
[ 0  2  4  7  8 16]


In [3]:
# Alphabetical sorting

np2 = np.array(["john","hari","shyam","ram","gita","sita"])

print(np2)

print(np.sort(np2))  

['john' 'hari' 'shyam' 'ram' 'gita' 'sita']
['gita' 'hari' 'john' 'ram' 'shyam' 'sita']


In [4]:
# Boolean sorting

np3 = np.array([True,False,False,True])

print(np3)

print(np.sort(np3))  

[ True False False  True]
[False False  True  True]


In [6]:
# 2-D array sorting

np4 = np.array([[9,3,5,2],[2,7,5,3]])

print(np4)

print(np.sort(np4))  # individual elements inside each rows are sorted

[[9 3 5 2]
 [2 7 5 3]]
[[2 3 5 9]
 [2 3 5 7]]
