# Searching

In [1]:
import numpy as np 

In [8]:
np1 = np.array([1,2,3,4,5,6,7,8,9,10,3])

print(np1)
 
# Using where method

x = np.where(np1 == 3)
print(x)

# where retrurns a tuple ,gives the index no of the data found

print(x[0])

print(np1[x[0]]) # returns the data 

[ 1  2  3  4  5  6  7  8  9 10  3]
(array([ 2, 10]),)
[ 2 10]
[3 3]


In [14]:
# to return even numbers

y = np.where( np1 % 2 == 0)
print(np1)
print(y) # gives the indexes of even numbers

[ 1  2  3  4  5  6  7  8  9 10  3]
(array([1, 3, 5, 7, 9]),)
