# Filtering Numpy Arrays

In [1]:
import numpy as np

In [2]:
# filtering numpy arrays with Boolean index lists

np1 = np.array([1,2,3,4,5,6,7,8,9,10])
x = [True,True,False,False,False,False,False,False,False,False]

print(np1)
print(np1[x])

[ 1  2  3  4  5  6  7  8  9 10]
[1 2]


In [3]:
filtered = []

for thing in np1:
    if thing % 2==0:
        filtered.append(True)
    else :
        filtered.append(False)
        
        
print(np1)

print(filtered)

print(np1[filtered])

[ 1  2  3  4  5  6  7  8  9 10]
[False, True, False, True, False, True, False, True, False, True]
[ 2  4  6  8 10]


In [4]:
# Shortcut

filter = np1 % 2 == 0

print(np1)

print(filter)

print(np1[filter])

[ 1  2  3  4  5  6  7  8  9 10]
[False  True False  True False  True False  True False  True]
[ 2  4  6  8 10]
